MAX_IMG_WIDTH = 300
DISPLAY_WINDOW_NAME = "labeled image"

LABEL_DIRECTORY = "labeledData"
COMPRESS_DIRECTORY = "compressed"
TRAINING_DATA_DIRECTORY = "toBeLabeled"
LABELED_IMAGES_DIRECTORY = "transformedImages"
OVERLAP_THREASHOLD = 1
